### ISSUE TITLE
How about release a .exe program with pyinstaller?

### ISSUE THREAD

**Issue by Leslie-Wong-H** [romanodev/OpenBTE#1]
Hello！🤗👋Mr. Romano.
Recently I came to know the pyinstaller library, and found it quite fantastic to convert py scripts to .exe program. 
With the help of it, I successfully release some programs to users without any knowledge about python.
By releasing a .exe program, OpenBTE can be more accessible to users in Windows without installing Anaconda.
Therefore, I strongly recommand this to you, my dear teacher.
😊😊😊
Have a try~
😚

**Comment by Leslie-Wong-H** [comment]
Since Mr.Romano is a typical Linux user and it is me who comes up with the idea of .exe release, I think it would be better that I fork this repository, supplement the .exe release and, if available,  make a pull request.

Ok, I'll have a try. 
o(*￣︶￣*)o

**Comment by romanodev** [comment]
Great! Let me know how it goes. I will look into it as well

**Comment by romanodev** [comment]
There is no immediate plan for releasing an .exe version. I will close the issue.
