### ISSUE TITLE
Win10 conda install -c conda-forge -c gromano openbte not working?

### ISSUE THREAD

**Issue by Leslie-Wong-H** [romanodev/OpenBTE#2]
Try execute openBte in my win10. Having MSMPI V10.0 installed, yet it does not works with the command line "conda install -c conda-forge -c gromano openbte". 
The error images are as follows. Any idea about what was going wrong?
![image](https://user-images.githubusercontent.com/27696701/67622958-27c8f980-f852-11e9-8eaf-07c7c295f3d1.png)
![image](https://user-images.githubusercontent.com/27696701/67622966-37e0d900-f852-11e9-9b9f-b02b10f81f6a.png)

**Comment by romanodev** [comment]
I am looking into it

**Comment by romanodev** [comment]
There is no immediate plans for making OpenBTE compatible with Windows. One option can be Docker, although it has not been tested yet. I will close the issue.
